#nginx-svc-np
apiVersion: v1
kind: Service
metadata:
  name: nc-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
  - nodePort: 31111
    port: 80
    targetPort: 80
  selector:
    app: nginx-app
